language: python
sudo: enabled
cache:
  directories:
    - $HOME/weights

matrix:
  include:
    - name: CUDA 9
      python: 3.6
      env:
        - CUDA=9.2.148-1
        - CUDA_SHORT=9.2
        - UBUNTU_VERSION=ubuntu1604
      dist: xenial


install:
  # Refer to https://github.com/jeremad/cuda-travis
  - INSTALLER=cuda-repo-${UBUNTU_VERSION}_${CUDA}_amd64.deb
  - wget http://developer.download.nvidia.com/compute/cuda/repos/${UBUNTU_VERSION}/x86_64/${INSTALLER}
  - sudo dpkg -i ${INSTALLER}
  - wget https://developer.download.nvidia.com/compute/cuda/repos/${UBUNTU_VERSION}/x86_64/7fa2af80.pub
  - sudo apt-key add 7fa2af80.pub
  - sudo apt update -qq
#  - sudo apt install -y cuda-core-${CUDA_SHORT/./-} cuda-cudart-dev-${CUDA_SHORT/./-} cuda-cufft-dev-${CUDA_SHORT/./-} cuda
  - sudo apt install -y cuda
  - sudo apt clean
  - export CUDA_HOME=/usr/local/cuda
  # for HysiaDecoder
  - export CUDA_PATH=$CUDA_HOME
  - export PATH=${CUDA_HOME}/include:${PATH}
  # fix libcuda.so.1 not found issue
  - sudo ln -s ${CUDA_HOME}/lib64/stubs/libcuda.so ${CUDA_HOME}/lib64/stubs/libcuda.so.1
  - export LD_LIBRARY_PATH=${CUDA_HOME}/lib64/stubs:${LD_LIBRARY_PATH}
  # Refer to https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/use-conda-with-travis-ci.html
  - sudo apt update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda env create -f environment.yml
  - travis_retry conda activate V2O
  # fix dependencies
  - pip install requests requests_futures h5py mmcv torchstat
  - sudo apt-get install libopenblas-dev
  - sudo apt-get install --reinstall libtheora0
  - export LD_LIBRARY_PATH=$HOME/miniconda/envs/V2O/lib:/usr/local/lib:/$LD_LIBRARY_PATH

script:
  - export CUDA_VISIBLE_DEVICES="-1"
  - export BUILD_FLAG="1"
  - export PYTHONPATH=$PYTHONPATH:$PWD/hysia::$PWD
  - bash scripts/download-data.sh
  - bash scripts/build.sh
  # `tests/test_build_classifier.py`: no target file.
  # `tests/test_search.py`: no TVQA dataset.
  # skip testing ray, clipper and tfs.
  # `test_monitor.py`: no GPU available in travis.
  # skip testing mmdet: pytorch needs to be upgraded to 1.x
  # `test_profiler/`: no target files.
  - python -m pytest --ignore=tests/test_monitor/test_monitor.py --ignore=tests/test_profiler/ --ignore=tests/test_build_classifier.py --ignore=tests/test_clipper/ --ignore=tests/test_tfs/ --ignore=tests/test_search.py --ignore=tests/test_clipper_mmdet.py --ignore=tests/test_mmdet.py --ignore=tests/test_product.py --ignore=tests/test_ray_tf.py tests/

notifications:
  email: false