# leave CUDA:0 in case of someone train models without checking GPU usage
decoder: CPU
visual_model_server: CPU:1
audio_model_server: CPU:2
feature_model_server: CPU:3
product_search_server: CPU:2
scene_search_server: CPU:3
