name: maskrcnn
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - asn1crypto=0.24.0
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2019.5.15
  - cairo=1.14.12
  - certifi=2019.6.16
  - cffi=1.12.3
  - chardet=3.0.4
  - cryptography=2.7
  - cudatoolkit=9.0
  - cycler=0.10.0
  - cython=0.29.13
  - dbus=1.13.6
  - expat=2.2.6
  - ffmpeg=4.0
  - fontconfig=2.13.0
  - freeglut=3.0.0
  - freetype=2.9.1
  - glib=2.56.2
  - graphite2=1.3.13
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - harfbuzz=1.8.8
  - hdf5=1.10.2
  - icu=58.2
  - idna=2.8
  - intel-openmp=2019.4
  - jasper=2.0.14
  - jpeg=9b
  - kiwisolver=1.1.0
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libglu=9.0.0
  - libopencv=3.4.2
  - libopus=1.3
  - libpng=1.6.37
  - libstdcxx-ng=9.1.0
  - libtiff=4.0.10
  - libuuid=1.0.3
  - libvpx=1.7.0
  - libxcb=1.13
  - libxml2=2.9.9
  - matplotlib=3.1.1
  - mkl_fft=1.0.14
  - mkl_random=1.0.2
  - ncurses=6.1
  - ninja=1.9.0
  - numpy=1.16.4
  - numpy-base=1.16.4
  - olefile=0.46
  - opencv=3.4.2
  - openssl=1.1.1d
  - pcre=8.43
  - pillow=6.1.0
  - pip=19.2.2
  - pixman=0.38.0
  - py-opencv=3.4.2
  - pycparser=2.19
  - pyopenssl=19.0.0
  - pyparsing=2.4.2
  - pyqt=5.9.2
  - pysocks=1.7.0
  - python=3.6.9
  - python-dateutil=2.8.0
  - pytorch=1.1.0
  - pytz=2019.2
  - qt=5.9.7
  - readline=7.0
  - requests=2.22.0
  - setuptools=41.0.1
  - sip=4.19.8
  - six=1.12.0
  - sqlite=3.29.0
  - tk=8.6.8
  - torchvision=0.3.0
  - tornado=6.0.3
  - tqdm=4.32.1
  - urllib3=1.24.2
  - wheel=0.33.4
  - xz=5.2.4
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - fastapi==0.36.0
    - python-multipart==0.0.5
    - pyyaml==5.1.2
    - uvicorn==0.8.6
    - yacs==0.1.6
