- name: maskrcnn-service
  base_root: maskrcnn-service
  predictor: predictor.py
  engine: engine.py
  device: CUDA:1
  env:
    conda: environment.yml
    pre_install: sh install.sh
  grpc_port: 8000
  http_port: 8001
  engine_config: caffe2/e2e_faster_rcnn_R_50_C4_1x_caffe2
